name: Android CI - build custom APK

on:
  push:
    branches: [ "custom-apk" ]

permissions:
  contents: read

jobs:
  build:
    name: Build custom APK from project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout OsmAnd
      uses: actions/checkout@v3
      with:
        path: android
    - name: checkout OsmAnd-resources
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-resources
        path: resources
    - name: checkout OsmAnd-core
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-core
        path: core
    - name: checkout OsmAnd-core-legacy
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-core-legacy
        path: core-legacy
    - name: checkout OsmAnd-build
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-build
        path: build
    - name: checkout OsmAnd-tools
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-tools
        path: tools
    - name: checkout OsmAnd-misc
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-misc
        path: misc

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

#    - name: Adding my keystore file content from secret
#      run: |
#        cd keystores/ && echo "${{ secrets.MY_KEYSTORE_FILE_BASE64 }}" > ./my.keystore.encoded.txt && openssl base64 -d -in ./my.keystore.encoded.txt -out ./my.keystore && ls -al

    - name: Applying custom patch
      working-directory: ./android
      env:
        APP_VERSION: "4.5.0"          #
        APP_VERCODE: 4504             #
      run: |
        chmod +x ./.patch/prebuild*.sh   &&  \
        ./.patch/prebuild-only-rename.sh "$APP_VERSION" "$APP_VERCODE"

    - name: Get current date with timezone into env variable
      run: |
        echo "DATE_LAST_BUILD=$(TZ=':Europe/Bucharest' date +'%Y%m%d')" >> "$GITHUB_ENV"    && \
        echo "DATETIME_LAST_BUILD=$(TZ=':Europe/Bucharest' date +'%F\ %H:%M\ %Z')" >> "$GITHUB_ENV"

    - name: Patch memory requirements
      working-directory: ./android
      run: printf "\norg.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=4096m -XX:MaxHeapSize=8192m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8\n" >> gradle.properties

    # https://github.com/marketplace/actions/gradle-build-action
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/custom-apk' }}
        #gradle-version: 6.5    # 7.5.1 used as defined in gradle-wrapper.properties
        #option: '--no-build-cache'

    - name: Cleanup previous build directory
      working-directory: ./android
      run: ./gradlew clean

    - name: Build Android APK with Gradle
      working-directory: ./android
      env:
        TARGET_APP_NAME: "OsmAndDjBpF"
        APP_EDITION: "${{ env.DATETIME_LAST_BUILD }}"         # automatic
        APK_VERSION_SUFFIX: "#build${{ github.run_number }}"  # 4.5.0#build8
      run: ./gradlew  assembleNightlyFreeLegacyFatDebug

    - name: Rename APK
      working-directory: ./android
      run: mv OsmAnd/build/outputs/apk/nightlyFreeLegacyFat/debug/OsmAnd-nightlyFree-legacy-fat-debug.apk OsmAnd/build/outputs/apk/nightlyFreeLegacyFat/debug/OsmAnd-nightlyFree-legacy-fat-debug-$(git log -n 1 --format='%h').apk

    - name: Archive APK (Upload artifact)
      # only upload on pull request
      #if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v3
      with:
#        name: debug-src-of-custom-apk-build-${{ github.run_number }}
#        path: android/OsmAnd/build.gradle
#        path: android
        name: custom-osmand-apk-build-${{ github.run_number }}      # .zip will be added
        path: android/OsmAnd/build/outputs/apk/*/*/*.apk
        retention-days: 90
